name: "Sync Issues to Todoist"
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  create-task:
    runs-on: ubuntu-latest
    steps:
      - name: "Debug Event"
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          
      - name: "Create Todoist Task"
        uses: ptallen63/todoist-task-action@v1.0.3
        with:
          token: ${{ secrets.TODOIST_API_KEY }}