name: Todoist Sync

on:
  # Runs every day at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'
  # Allows manual trigger
  workflow_dispatch:
  # Runs when issues are modified
  issues:
    types: [opened, edited, closed, reopened, assigned]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup cache for sync data
      - uses: actions/cache@v3
        with:
          path: ./sync.json
          key: ${{ runner.os }}-todoist-sync

      # Sync with Todoist
      - name: Sync Issues to Todoist
        uses: simenandre/todoist-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_API_KEY }}
          query: 'is:open assignee:${{ github.repository_owner }}'
          sync-file-name: ./sync.json